# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Content-Security-Policy = "default-src 'self'; \
    script-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com https://www.google-analytics.com; \
    style-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; \
    font-src 'self' 'unsafe-inline' https://stackpath.bootstrapcdn.com; \
    img-src 'self' https://www.google-analytics.com https://stats.g.doubleclick.net; \
    connect-src https://www.google-analytics.com https://stats.g.doubleclick.net;"

[context.production.environment]
HUGO_VERSION = "v0.74.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

